#!/bin/bash

icons='{"1":"","2":"󰙯","3":"","4":"","5":""}'

spaces (){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    NO_ICONS=$(seq 1 5 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})')
    echo "$NO_ICONS" | jq -Mc --argjson icons "$icons" 'map(. + {"icon":$icons[.id]})'

}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
