#!/bin/sh

if [ "$1" = "up" ] ; then
    hyprctl dispatch workspace $(($(hyprctl monitors -j | jq --raw-output .[0].activeWorkspace.id)+1))
elif [ "$1" = "down" ] ; then
    hyprctl dispatch workspace $(($(hyprctl monitors -j | jq --raw-output .[0].activeWorkspace.id)-1))
fi
